R8169: Fix compilation error when RTL8169_DEBUG is defined
Fixed following compilations error :
r8169.c: In function `rtl8169_print_mac_version':
r8169.c:458: parse error before '}' token
r8169.c:462: parse error before '}' token
r8169.c: In function `rtl8169_print_phy_version':
r8169.c:501: parse error before '}' token
r8169.c:505: parse error before '}' token
r8169.c: In function `rtl8169_hw_phy_config':
r8169.c:552: parse error before '}' token
r8169.c:553: parse error before '}' token
r8169.c: In function `rtl8169_init_one':
r8169.c:880: parse error before '}' token
r8169.c:884: parse error before '}' token
r8169.c:889: parse error before '}' token
r8169.c:891: parse error before '}' token
r8169.c: In function `rtl8169_hw_start':
r8169.c:1136: parse error before '}' token
make[2]: *** [r8169.o] Error 1

Signed-off-by: Jaswinder Singh Rajput <jaswinderrajput@gmail.com>
Signed-off-by: Willy Tarreau <w@1wt.eu>